### ISSUE TITLE
Need to update with AWS NodeJS12.x runtime

### ISSUE THREAD

**Issue by sandaemc** [adieuadieu/serverless-chrome#244]
Error:

```
Serverless plugin "serverless-plugin-chrome" initialization errored: The "serverless-plugin-headless-chrome" plugin only supports the Node.js 6.10 or 8.10 runtimes. Your service is using the "nodejs12.x" provider.
```

**Comment by iocentos** [comment]
Same here.

This is from amazon
`
An error occurred: HelloLambdaFunction - The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
`

This is from the chrome plugin
`
Error: The "serverless-plugin-headless-chrome" plugin only supports the Node.js 6.10 or 8.10 runtimes. Your service is using the "nodejs12.x" provider.
`

**Comment by adieuadieu** [comment]
I've published serverless-plugin-chrome@1.0.0-55.1 with a quickfix.

**Comment by 00dev** [comment]
I'm afraid that quickfix is not enough. It's need to add elements into `wrapperTemplateMap` in packages/serverless-plugin/src/index.js
```
const wrapperTemplateMap = {
  'aws-nodejs6.10': 'wrapper-aws-nodejs.js',
  'aws-nodejs8.10': 'wrapper-aws-nodejs.js', 
  'aws-nodejs10.x': 'wrapper-aws-nodejs.js',
  'aws-nodejs12.x': 'wrapper-aws-nodejs.js',
}
```

**Comment by rauluranga** [comment]
same here, i got the same error as well on AWS:
```
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
```

**Comment by adieuadieu** [comment]
Closing this issue as it was fixed by @evgeniyannenkov in #244.

**Comment by safv12** [comment]
I'm still getting the error but with the `serverless-plugin-headless-chrome` plugin:

```
Error: The "serverless-plugin-headless-chrome" plugin only supports the Node.js 6.10 or 8.10 runtimes. Your service is using the "nodejs12.x" provider.
```

**Comment by safv12** [comment]
Sorry, It was my error, I just updated to `serverless-plugin-chrome@1.0.0-55.2` and it works.

**Comment by link365dev** [comment]
@adieuadieu Kindly update the template also: https://github.com/adieuadieu/serverless-chrome/blob/master/examples/serverless-framework/aws/package.json

Because fresh installations are still getting the error.

**Comment by k-bx** [comment]
@link365dev I'm trying to set things up on a fresh install, that file you've pointed to has `"serverless-plugin-chrome": "1.0.0-70",` in it, while there's no `1.0.0-70` version published. Who's mistake is it?
